from enum import Enum


class UserRole(str, Enum):
    ADMIN = "ADMIN"
    OPERATOR = "OPERATOR"
    VIEWER = "VIEWER"


class MachineStatus(str, Enum):
    ONLINE = "ONLINE"
    OFFLINE = "OFFLINE"
    NEVER_CONNECTED = "NEVER_CONNECTED"
    AGENT_UNHEALTHY = "AGENT_UNHEALTHY"


class AgentStatus(str, Enum):
    PENDING = "PENDING"
    ACTIVE = "ACTIVE"
    REVOKED = "REVOKED"


class AlertSeverity(str, Enum):
    INFO = "INFO"
    WARNING = "WARNING"
    CRITICAL = "CRITICAL"


class AlertStatus(str, Enum):
    OPEN = "OPEN"
    ACKNOWLEDGED = "ACKNOWLEDGED"
    RESOLVED = "RESOLVED"


class TopologyStatus(str, Enum):
    DETECTED = "DETECTED"
    PARTIAL = "PARTIAL"
    UNKNOWN = "UNKNOWN"


class FieldConfidence(str, Enum):
    DETECTED = "DETECTED"
    REPORTED = "REPORTED"
    UNKNOWN = "UNKNOWN"


class EventType(str, Enum):
    MACHINE_REGISTERED = "MACHINE_REGISTERED"
    MACHINE_ONLINE = "MACHINE_ONLINE"
    MACHINE_OFFLINE = "MACHINE_OFFLINE"
    MACHINE_UNHEALTHY = "MACHINE_UNHEALTHY"
    RAM_ADDED = "RAM_ADDED"
    RAM_REMOVED = "RAM_REMOVED"
    RAM_CHANGED = "RAM_CHANGED"
    GPU_ADDED = "GPU_ADDED"
    GPU_REMOVED = "GPU_REMOVED"
    GPU_CHANGED = "GPU_CHANGED"
    DISK_ADDED = "DISK_ADDED"
    DISK_REMOVED = "DISK_REMOVED"
    DISK_CHANGED = "DISK_CHANGED"
    CPU_CHANGED = "CPU_CHANGED"
    MOTHERBOARD_CHANGED = "MOTHERBOARD_CHANGED"
    BIOS_CHANGED = "BIOS_CHANGED"
    NETWORK_ADAPTER_CHANGED = "NETWORK_ADAPTER_CHANGED"
    IP_CHANGED = "IP_CHANGED"
    PCIE_CHANGED = "PCIE_CHANGED"


class NotificationChannel(str, Enum):
    DASHBOARD = "DASHBOARD"
    EMAIL = "EMAIL"
    WEBHOOK = "WEBHOOK"
    TELEGRAM = "TELEGRAM"
    SLACK = "SLACK"
    TEAMS = "TEAMS"
